simplex-chat/simplex-chat

edge-messaging-implementation.md, edge-messaging.md
- explain why sender/receiver different
- removed ID from sender requests
- remove ability to change URIs:
- not really needed (as the whole connection can be replaced)
- creates risk of losing the connection in case of client failure
=> Connection URIs

.github/workflows/ci_dart.yml, packages/repo_support/.gitignore, packages/repo_support/README.md, packages/repo_support/pubspec.yaml, packages/repo_support/tool/run_ci.dart
This is a pull request to get me started. I'm not sure about the convention you use (you seem to create branch from v5 using a path looking like user/feature) so I'm trying to mimic your behavior. Here the CI simply check format, lints and run unit test on all platform (mac, windows, linux) and all flutter version (stable, beta, dev). We might choose to allow failure on dev as sometimes there are changes that could break the linter.
Let me know if I get anything wrong.
=> build: setup dart simple ci using github actions

apps/ios/Shared/Views/Helpers/ImagePicker.swift, apps/ios/Shared/Views/UserSettings/UserProfile.swift
Update the image picker to the newer and more private [`PHPicker`](https://developer.apple.com/videos/play/wwdc2020/10652/)
This then separates camera image selection and image selection from gallery.
Note: This also improves privacy as the `PHPicker` runs in a separate process and only shares selected images with the SimpleX app rather than the full library of images.
=> ios: update image picker

apps/android/app/src/main/java/chat/simplex/app/SimplexService.kt, apps/android/app/src/main/res/values-ru/strings.xml, apps/android/app/src/main/res/values/strings.xml
Now users are able to hide a notification without finding the app in the settings. At least now they will be aware of such possibility. I could write `setup` instead of `hide` (which is closer to actual situation) but in this case users could misunderstand of what they will be trying to setup.
=> Button in notification that routes to settings for notification channel

apps/android/.gitignore, apps/android/app/build.gradle, apps/android/app/src/main/AndroidManifest.xml, apps/android/app/src/main/java/chat/simplex/app/SimplexApp.kt, apps/android/build.gradle
- now debug builds will have `.debug` suffix by default. It allows to have multiple app builds (debug and release) on the same device. If you don't need this, create a file local.properties and add `application_id_suffix=` into it
- now everyone can override some variables from top-level build.gradle file. For example, gradle_plugin_version, debuggable manifest attribute, and so on. Overriding Gradle plugin version is useful for those who uses Intellij IDEA with older Gradle plugin than in Android Studio.
There is no behaviour changes for release build and no changes in versions of plugins/libs. 
There is a change for debug build which can be easily returned to previous behavior by adding `application_id_suffix=` into local.properties file.
=> Debug package suffix and ability to override Gradle variables

apps/android/app/src/main/java/chat/simplex/app/MainActivity.kt, apps/android/app/src/main/java/chat/simplex/app/model/ChatModel.kt, apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatView.kt, apps/android/app/src/main/java/chat/simplex/app/views/chatlist/ChatListNavLinkView.kt
- scroll position when you open keyboard/change screen orientation will remain the same
- scrolling to top will show messages from history
- unread messages will be positioned at the top of the screen
=> Endless scrolling in a chat view

apps/android/app/build.gradle, apps/android/app/src/main/AndroidManifest.xml, apps/android/build.gradle, scripts/android/compress-and-sign-apk.sh
- can reduce from 200mb to 50mb with level 5 of compression. Supports Intellij IDEA and command line gradle invocation
- by default, this feature is disabled. To enable create a file local.properties in `apps/android` and paste this line: `compression_level=5`
- level can be from 0 (no compression) to 9 (slowest and the must effective)
- automatically enables `extractNativeLibs` AndroidManifest's flag since it's required in this case. Feel free to find an alternative that works with compression of .so libs and without enabling this flag
- Windows is not suppored, of course. Only Unix-like OSes
=> Different level of APK compression

apps/android/app/src/main/java/chat/simplex/app/views/chat/item/EmojiItemView.kt
- Regex for Emoji: old solution is working incorrectly with, for example, Japan characters. This one should be better in all aspects
=> android: fix hieroglyphs showing as emojis

apps/android/app/src/main/java/chat/simplex/app/MainActivity.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatInfoView.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatView.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/ComposeView.kt, apps/android/app/src/main/java/chat/simplex/app/views/helpers/SearchTextField.kt
…n orientation change
- restore message text as well as reply state
- restore search view
- don't display blank view on orientation change for a moment
- better saving of local user name while typing. Prevent loosing state on orientation change and hard killing the app
- don't display same messages in MainActivity from old intents on orientation change (no double processing of intent)
=> android: preserving state for orientation change

src/Simplex/Chat.hs, src/Simplex/Chat/Store.hs, tests/ChatTests.hs
- Fully delete member record without items when removing member
- Fully delete removed/left/"group deleted" member records without items when expiring messages
- Delete “unused” group contact when deleting member
=> core: update deleteGroupMember logic and its usages (no items & expiration)

apps/ios/Shared/Views/ChatList/ChatListNavLink.swift, src/Simplex/Chat.hs, src/Simplex/Chat/Migrations/M20220101_initial.hs, src/Simplex/Chat/Migrations/chat_schema.sql, src/Simplex/Chat/Store.hs
for reference:
table | field | used for incognito profiles
---|---|---
contacts | contact_profile_id | -
group_members | contact_profile_id | -
group_members | member_profile_id | +
contact_requests | contact_profile_id | -
groups | host_conn_custom_user_profile_id | - (not used at all)
connections | custom_user_profile_id | +
=> core: clean up incognito profiles

apps/android/app/src/main/java/chat/simplex/app/views/chat/ComposeView.kt, apps/android/app/src/main/res/values-de/strings.xml, apps/android/app/src/main/res/values-ru/strings.xml, apps/android/app/src/main/res/values/strings.xml
Catch drawable's DecodeException that can happen on some devices for unknown reason. Exception has a message "Failed to create image decoder with message 'unimplemented'Input contained an error." so looks like the user use some non-popular image format that is not implemented in Android's ImageDecoder.
=> android: catch DecodeException

apps/android/app/src/main/java/chat/simplex/app/views/usersettings/Cryptor.kt, apps/android/app/src/main/res/values-de/strings.xml, apps/android/app/src/main/res/values-ru/strings.xml, apps/android/app/src/main/res/values/strings.xml
Restoring app's data from backup tools will still allow to enter passphrase instead of just crashing like it was before. When restoring happens, keys from keystore gets deleted and the app wasn't ready for this situation
(cherry picked from commit 256243dc8c8e0b8547d794624c1d0f256f1ac5f2)
=> android: fix crash on restoring from backup

apps/android/app/src/main/java/chat/simplex/app/SimplexService.kt, apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt, apps/android/app/src/main/java/chat/simplex/app/views/call/CallView.kt, apps/android/app/src/main/java/chat/simplex/app/views/database/DatabaseView.kt, apps/android/app/src/main/java/chat/simplex/app/views/usersettings/NotificationsSettingsView.kt
Fixes ForegroundServiceDidNotStartInTimeException that could happen when a code starting a service and then quickly stops it until it has created. This situation was stopping the service from running startForeground function, which is required by Android.
(cherry picked from commit a5d235e559edec51204c1551d20ee4aaddb8588f)
=> android: fix ForegroundServiceDidNotStartInTimeException

PRIVACY.md, README.md
I noticed these couple of links to a .html file in your repository. I think these should either link to the full blog article, or the markdown file.
=> docs: Fix dead links to audit

src/Simplex/Chat/Controller.hs, tests/ChatTests.hs
- set limit to send files without acceptance to 6 chunks (same as released limit to receive).
- increase limit to receive files sent without acceptance to 8 chunks (as iOS voice messages seem to be bigger, and currently limited to 30 sec).
- tests
=> core: config to send inline files

apps/android/app/src/main/java/chat/simplex/app/views/usersettings/Cryptor.kt
When restoring from Titanium Backup I found that the app crashing since decryption info was different from the info I had in backup. This code prevent crash and allows to enter decryption passphrase again
=> android: Prevent possible crash while decrypting DB after restore

scripts/cabal.project.local.mac
`cabal update` would fail complaining about an unrecognized `#` character
=> fix incorrect comment syntax in cabal.project.mac

apps/android/app/src/main/java/chat/simplex/app/model/ChatModel.kt, apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatView.kt, apps/android/app/src/main/java/chat/simplex/app/views/chat/item/ChatItemView.kt, apps/android/app/src/main/res/values/strings.xml, apps/ios/Shared/Model/SimpleXAPI.swift, apps/ios/Shared/Views/Chat/ChatView.swift, apps/ios/SimpleXChat/APITypes.swift, apps/ios/SimpleXChat/ChatTypes.swift, src/Simplex/Chat.hs, src/Simplex/Chat/Controller.hs, src/Simplex/Chat/Types.hs, src/Simplex/Chat/View.hs, tests/ChatTests/Files.hs
backend fixes:
- check file is not complete on CancelFile,
- check file is not cancelled when processing XFTP events,
- mark SMP file cancelled if recipient cancelled in direct chat.
=> ios, android: cancel file UI; core: cancel file fixes

docs/SERVER.md, docs/WEBRTC.md, docs/XFTP-SERVER.md, docs/lang/cs/SERVER.md, docs/lang/cs/WEBRTC.md, docs/lang/fr/SERVER.md, docs/lang/fr/WEBRTC.md
I think the lack of `sudo` was an oversight and I know that not specifying port for `ufw` opens both TCP and UDP, while I was told at SimpleX that the server only uses TCP.
=> docs/SERVER: use sudo, specify protocol  & add Fedora

src/Simplex/Chat/Mobile.hs
GHC's rts tries to obtain the encoding from iconv, however this is not really available on iOS. It therefore defaults to US-ASCII, and then breaks with unicode data. We now explicitly set this to utf-8 here.
=> core: explicitly set encoding to utf-8 (fixes unicode filenames on mobile)

website/src/blogs-atom-feed.njk, website/src/blogs-rss-feed.njk
Noticed that the blog source URL is incorrectly set and has a comma that breaks the URL.
=> Fix broken RSS feed source URL

Dockerfile
The docker image was not updated to use ghc 9.6, this PR updates it using the versions from the github workflows.
=> cli: update docker image to use ghc 9.6.2

cabal.project, scripts/nix/sha256map.nix, src/Simplex/Chat/Controller.hs, src/Simplex/Chat/Remote.hs, src/Simplex/Chat/Remote/Types.hs, stack.yaml, tests/RemoteTests.hs
Otherwise HTTP server is leaking connections and session is inconsistent.
=> core: terminate remote control TLS connection on both sides

src/Simplex/Chat.hs, src/Simplex/Chat/Controller.hs, src/Simplex/Chat/Remote.hs, src/Simplex/Chat/View.hs, tests/RemoteTests.hs
Commands use the same action, made idempotent and don't send events.
=> Send CRRemote*Stopped on all errors

src/Simplex/Chat.hs, src/Simplex/Chat/Remote.hs
Avoid cancelling asyncs that just crashed and invoked the handler.
=> core: fix circular error handling in remote connection

apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/platform/PlatformTextField.desktop.kt
The following PR adds the ability, on Desktop, to paste images from the clipboard into the send message input box.
Tested On:
1. Ubuntu
Supported image formats (all I've tested so far):
1. png
2. jpg
3. webp
4. bmp
Unsupported image formats:
1. svg
2. gif (It displays but does not transition between frames)
=> desktop: add image pasting from clipboard

src/Simplex/Chat/Options.hs
`-e` is already used for `--execute`
=> cli: remove clashing short option for device-name

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/ui/theme/Theme.kt
With such a theme (important color here is a `menus` ) text colors become opposite of what we expect (white on light theme). This PR fixes it by specifying default color that can be overriden in any place of code.
See for more info: https://github.com/simplex-chat/simplex-chat/issues/3363
Closes https://github.com/simplex-chat/simplex-chat/issues/3363
```yaml
base: "LIGHT"
colors:
accent: "#ff8839ef"           # mauve
accentVariant:: "#ff4c4f69"   # text
secondary: "#ff8839ef"        # mauve
secondaryVariant: "#ff4c4f69" # text
background: "#ffeff1f5"       # base
menus: "#ff8839ef"            # mauve
title: "#ff8839ef"            # mauve
sentMessage: "#ff4c4f69"      # text
receivedMessage: "#ff4c4f69"  # text
```
=> android, desktop: specifying text color globally

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/AlertManager.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/ModalView.kt
To reproduce the problem add to SimpleXAPI.startChat():
```kotlin
ModalManager.fullscreen.showCustomModal {}
AlertManager.shared.showAlertMsg(
title = "lalal",
text = "lalal"
)
```
=> android, desktop: fix alerts/modals when they are shown before UI init

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/ChatModel.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/usersettings/NetworkAndServers.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/usersettings/ProtocolServersView.kt
- deleting the last server triggered restoration of previously saved servers
- buttons for reset and save were showing wrong enabled/disabled state when disconnects remote on that screen
=> android, desktop: protocol servers fix

apps/ios/Shared/Model/ChatModel.swift, apps/ios/Shared/Views/Chat/ChatItemMenu/ChatItemMenu.Allowed.swift, apps/ios/Shared/Views/Chat/ChatItemMenu/ChatItemMenu.Buttons.swift, apps/ios/Shared/Views/Chat/ChatItemMenu/ChatItemMenu.swift, apps/ios/Shared/Views/Chat/ReverseList/ReverseList.Controller.swift, apps/ios/Shared/Views/Chat/ReverseList/ReverseList.HostingCell.swift, apps/ios/Shared/Views/Chat/ReverseList/ReverseList.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.AlignmentContainer.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.Item.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.ItemView.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.Sheet.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.TimelineView.swift, apps/ios/Shared/Views/Chat/Timeline/Timeline.swift, apps/ios/SimpleX.xcodeproj/project.pbxproj, apps/ios/SimpleXChat/ChatTypes.swift
Part of `Timeline` feature:
1. [Hashable Conformance](https://github.com/simplex-chat/simplex-chat/pull/4348)
2. [Views](https://github.com/simplex-chat/simplex-chat/pull/4350)
3. [Integration](https://github.com/simplex-chat/simplex-chat/pull/4351)
The current timeline implementation has high CPU and battery usage during scrolling,
which can result in dropped frames.
This is especially evident:
- In [Low Power Mode](https://support.apple.com/en-us/101604)
- On an Older Device (The app still supports [1st gen iPhone SE](https://en.wikipedia.org/wiki/IPhone_SE_(1st_generation)))
- When ChatItems include media or files
There are two main causes:
The current cell dequeuing implementation causes the whole view hierarchy to be reevaluated, for every loaded cell. 
While SwiftUI will reuse the …
=> iOS Timeline: 2. Views

docs/XFTP-SERVER.md
Systemd itself uses %<something> tokens so %% needs to be used for specifiers
(https://www.freedesktop.org/software/systemd/man/latest/systemd.unit.html)
=> docs: fix example systemd service unit in xftp-server documentation page

apps/ios/Shared/Views/Chat/ChatItem/CIGroupInvitationView.swift, apps/ios/Shared/Views/Chat/ChatItem/CIInvalidJSONView.swift, apps/ios/Shared/Views/Chat/ChatItem/CIRcvDecryptionError.swift, apps/ios/Shared/Views/Chat/ChatItem/DeletedItemView.swift, apps/ios/Shared/Views/Chat/ChatItem/FramedItemView.swift, apps/ios/Shared/Views/Chat/ChatItem/IntegrityErrorItemView.swift, apps/ios/Shared/Views/Chat/ChatItem/MarkedDeletedItemView.swift, apps/ios/Shared/Views/Chat/ChatItemInfoView.swift, apps/ios/Shared/Views/Chat/ChatView.swift, apps/ios/Shared/Views/Chat/ReverseList.swift, apps/ios/Shared/Views/Helpers/ChatItemClipShape.swift, apps/ios/SimpleX.xcodeproj/project.pbxproj
1. Preview for items without frame clipped.
2. During context menu animation shadow is missing corner radius:
3. After context menu animation finishes - default preview corner radius does not match the item:
All of the issues can be addressed by
- Ensuring that clipping is applied right before `.contextMenu` modifier
- providing a `.contentShape(.contextMenuPreview)`
There is another glitch, which happens when the height of chat item is less than 2x hardcoded corner radius.
This can happen, when user has set a different text size using `Dynamic Type` (This is used by surprisingly high percentage of users).
This is addressed by using a custom shape - which properly collapses into a pill, in this situation.
=> ios: make message corners rounded when selecting context menus

apps/ios/Shared/Model/ChatModel.swift, apps/ios/Shared/Model/SimpleXAPI.swift, apps/ios/Shared/Views/Chat/ChatView.swift
This PR includes two optimisations that improve the performance when marking items as read:
1. Precalculate indices, which is `O(n)` operation on a background thread.
2. Remove unnecessary `@State`, from `ChatItemWithMenu` what was causing additional `body` re-evaluations.
3. Remove `chatView` reference, because structs are passed as copy - so we where essentially creating a copy of `ChatView` for each loaded `ChatItemWithMenu` view.
* Also revert the scroll to bottom behaviour to always scroll till the end of the list.
=> ios: optimise mark-as-read performance

cabal.project, scripts/nix/sha256map.nix, src/Simplex/Chat.hs, src/Simplex/Chat/Controller.hs, src/Simplex/Chat/Options.hs, src/Simplex/Chat/Terminal.hs, src/Simplex/Chat/Terminal/Main.hs, src/Simplex/Chat/View.hs
Enabling socks proxy with --socks-mode=onion in directory service bot will allow users with onion-only relays joining the groups
=> cli: option to only use SOCKS5 proxy with onion-only relays

apps/ios/SimpleX SE/ShareAPI.swift, apps/ios/SimpleX SE/ShareModel.swift, apps/ios/SimpleXChat/ImageUtils.swift
- Adds utility for downsampling an image directly from disk instead of loading the original image in memory
- Adds support for sending image messages from share extension
https://github.com/user-attachments/assets/7fd2e161-d8d1-4d65-8d49-85a116d506a9
=> ios: add image message sending to share extension

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/ChatModel.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatInfoView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/group/GroupChatInfoView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/group/GroupMemberInfoView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/contacts/ContactsView.kt, apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml
Current context menus (...) on individual chats and groups have been a source of confusion for users and are generally missed as valuable features.
Remove confusion and complication associated with ... menus and increase interaction speed.
Keep only 1 action button per chat type (add member for groups, phone call for individual chats
- search
- call
- video
- mute
- message
- call
- video
- search
- add member
- mute
https://github.com/user-attachments/assets/d3324fe7-9a9d-41a1-902e-1a6a25efe9c7
https://github.com/user-attachments/assets/271e102f-7e49-405b-a954-c8296c7eb8c6
=> android, desktop: contacts, groups and group member action buttons

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatInfoView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/contacts/ContactListNavView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/contacts/ContactsView.kt, apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml
Drive deletion logic by contact type across screen (chat list, contact card, contact list) as opposed to based on screen context.
Delete bring up 2 options:
1. Only delete conversation (show text saying that It can be recovered in new chat sheet)
2. Delete contact
2a) Keep conversation toggle, should be off by default
2b) Buttons delete and notify contact and delete without notification
Delete brings confirmation
1) Buttons delete and notify contact and delete without notification
(Can be someone that deleted me, can be a contact deleted with conversation kept)
Delete brings alert
1) Confirm deletion (Confirm/Delete button)
=> android, desktop: streamlined delete actions based on contact type

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/UserPicker.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/contacts/ContactListNavView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/CloseSheetBar.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/ModalView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatSheet.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatView.kt
=> android: smaller new chat button in 1-hand UI mode, line on the correct side of the bar

apps/ios/Shared/Views/ChatList/ChatListNavLink.swift, apps/ios/Shared/Views/Helpers/SwipeLabel.swift, apps/ios/SimpleX.xcodeproj/project.pbxproj
Since we don't have control of the layout of views in the swipe action:
1. Create a UIView that mimics the layout of `Label` in swipe action context and handles localisation
2. Create a snapshot of the view. (Invert if neccessary)
3. Pass already rasterised view as the template image for the swipe action.
https://github.com/user-attachments/assets/cac5edb6-d0cb-4d4c-8217-be9929acca38
=> ios: invert swipe actions in oneHandUI mode

apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.android.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/SimpleXAPI.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ShareListNavLinkView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ShareListView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/contacts/ContactListNavView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatSheet.kt, apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml, apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.desktop.kt
=> android: one hand UI fixes and improvements

apps/ios/Shared/Views/ChatList/ChatListNavLink.swift, apps/ios/Shared/Views/ChatList/ContactConnectionView.swift
Fixes "You invited a contact" sheet having incorrect styling, when invoked from the "link" icon.
Extends the tap gesture to the whole navigation link using `.contentShape(Rectangle())`, so that the second sheet is no longer required.
=> ios: fix pending connection sheet styling when opened via icon; fix tappable area of pending connections and contact requests

apps/ios/Shared/Model/SimpleXAPI.swift, apps/ios/Shared/SimpleXApp.swift, apps/ios/Shared/Views/Call/CallController.swift, apps/ios/Shared/Views/ChatList/UserPicker.swift
Moves all of the api calls (excpt `apiActivate`), which occur on main thread during entering foreground:
- `apiGetCallInvitations`
- `apiGetChats`
- `apiListUsers`
Further improvements:
- `apiActivate` chat remains sync due to it occurring in `suspendLockQueue.sync` block.
- `ChatModel.updateChats(with newChats: [ChatData])` does processing in nested loops, potentially degrading performance when many chats are added.
=> ios: asynchronous api calls when entering foreground

apps/ios/Shared/Views/Chat/ReverseList.swift
Manually sets the right offset, when items are loaded into an empty list
=> ios: fix last message being hidden on load

apps/ios/Shared/Views/NewChat/NewChatMenuButton.swift, apps/ios/SimpleX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/ChatListNavLinkView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatSheet.kt
Our identification of contact cards was incorrect, because of that some deletion of conversation was missidentified as contact cards.
To reproduce the issue in `stable`
1. Create a new profile
2. Create a public address for the profile, and share the link with contacts
3. Go to your main profile and add the profile with the link from step 2.
4. Accept the invitation from the new profile
5. Delete the new profile, including server connections
6. In your main profile, delete contact and keep conversation
=> multiplatform: fix deleted contacts with conversations being identified as contact cards

docs/DOWNLOADS.md
It keeps getting outdated, maybe better to remove the version number.
=> docs: remove outdated latest version number from downloads

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatView.kt
To match ios behaviour.
There was also an issue where if someone did have the pref for incognito turned on (by for example toogle on group creation) it would be impossible to stop having incognito as the default on profile picker
=> android, desktop: reset incognito on profile picker

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatView.kt
Fixes such issue:
- on desktop open new chat sheet -> create new link
- close by pressing on center (in master it doesn't pass check on modal number and cleanup is not done)
- open new chat sheet and go to link creation again - same link is shown
=> desktop: cleanup current invitation when closing new chat sheet by pressing on center modal

apps/ios/Shared/Theme/Theme.swift, apps/ios/Shared/Views/Chat/ComposeMessage/ComposeView.swift, apps/ios/Shared/Views/Chat/Group/GroupProfileView.swift, apps/ios/Shared/Views/NewChat/AddGroupView.swift, apps/ios/Shared/Views/UserSettings/UserProfile.swift, apps/ios/SimpleX SE/ShareModel.swift, apps/ios/SimpleXChat/ImageUtils.swift
Affects:
- Create group
- Edit group profile
- Send video or image
- Share video or image
Does not affect:
- Link preview generation
- Wallpaper decoding
=> ios: prevent image encoding from blocking the UI

apps/ios/Shared/Views/ChatList/ChatListView.swift
in some rare cases the following can happen as a race condition:
- Stop chat and delete database
- Go to migrate to another device
- Press back
- App can crash
In some cases it does happen that the next iteration of `getSubsTotal` will run between stages where app state is active but controller is being rebuilt and chat is still stopped. It is safer that this task also checks that the chat is running as there is no guarantee that `AppChatState` being active means the chat isn't actually stopped
=> ios: fix ocassional error on getSubsTotal

apps/ios/Shared/Views/NewChat/NewChatView.swift
Tested when permission is enabled and disabled, it replicates the behaviour that happens when this view is open directly from new chat sheet
=> ios: fix empty qr code reader when swapping to connect via link

packages/simplex-chat-client/typescript/examples/squaring-bot.js, packages/simplex-chat-client/typescript/package.json, packages/simplex-chat-client/typescript/src/client.ts, packages/simplex-chat-client/typescript/src/command.ts, packages/simplex-chat-client/typescript/src/response.ts
As far I understand, recently you could send one message at once, now it changed and SDK wasn't able to handle properly message sending \ receiving (it just crushes). I fix it, so instead of sending \ receiving single message now you send \ receive array of messages at once
=> desktop: fix typescript sdk ability to send / receive messages

apps/multiplatform/android/src/main/java/chat/simplex/app/views/call/CallActivity.kt, apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/helpers/Locale.kt, apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/views/call/CallView.android.kt
There is a bug on Android related to including WebView. App language changes to system language regardless of what was set before in context's configuration. Re-set needed to be done twice: after creating of WebView and after removing it from a view
https://issuetracker.google.com/issues/109833940
=> android: re-apply custom language when webview appears

apps/multiplatform/common/src/commonMain/resources/assets/www/call.js, packages/simplex-chat-webrtc/src/call.ts
There is a problem related to managing selected audio output device in call. When microphone is disabled, WebView turns speaker on without need. No way to prevent it was found yet. This is temporary workaround that makes everything work except it makes microphone icon visible in status bar (microphone is not used actually in that moment)
=> android, desktop: don't stop audio track on Android in calls

apps/ios/Shared/Views/Chat/ChatView.swift, apps/ios/Shared/Views/Helpers/ChatItemClipShape.swift, apps/ios/Shared/Views/UserSettings/AppearanceSettings.swift
The tail looked very different from other items, and at the time we were doing it on ios we agreed this shouldn't show unless revealed, forgot to apply the same logic on ios
=> ios: dont show tails for moderated and blocked items unless revealed

apps/ios/Shared/Views/Helpers/ThemeModeEditor.swift, apps/ios/Shared/Views/UserSettings/AppearanceSettings.swift
Fix `.fileImporter` modifier not working in iOS15.* by attaching it higher in the view hierarchy - outside of the containing `List`.
=> ios: fix theme import file picker

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chatlist/UserPicker.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/usersettings/UserProfilesView.kt, apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml
=> desktop, android: user profiles move auth to change actions, show unread counts

apps/ios/Shared/Views/ChatList/UserPicker.swift, apps/ios/Shared/Views/UserSettings/UserProfilesView.swift
=> ios: user profiles move auth to change actions, show unread counts

apps/ios/Shared/Views/Onboarding/ChooseServerOperators.swift
Noticed the following while opening this view from what's new.
=> ios: fix alignment on operators review later button and notice

apps/ios/Shared/Model/NtfManager.swift, apps/ios/Shared/SimpleXApp.swift, apps/ios/Shared/Views/Chat/ChatItem/CIMemberCreatedContactView.swift
Steps:
- In ios, go to any chat in your profile
- Leave the app and lock the phone, wait for a minute or 2
- Send a message from another device and wait for notification to arrive
- Open from notification
Result:
- Chat header changes to contact/group associated with notification
- Chat message are from the chat you had open before locking the phone
open contact via "connected directly" chat item also replicates this issue
=> ios: fix open from notification and connected directly chat item chat loading

apps/ios/Shared/Views/Chat/ChatView.swift, apps/ios/Shared/Views/Chat/Group/GroupChatInfoView.swift, apps/ios/Shared/Views/Chat/Group/GroupMemberInfoView.swift
**The first issue I found was minor:**
- Be in a group with at least 2 members (can start with 2 owners)
- With the user on ios to navigate to the other user profile
- With the other user downgrade the role of ios user
- Nothing is updated on ios
- With the user on ios try to delete the user (or other button that isn't allowed anymore due to role downgrade)
Result: clicking some of these buttons does generate long errors that are very hard to parse for users, as simply binding group info fixed this issue decided to fix it here, but **happy to revert.**
**Found 2 issues while testing, driven by the fact we were duplicating group members by appending to the array of group members without adding to the groupMembersIndexes Map**
**1 way to reproduce:**
- Open a group with at least 3 members …
=> ios: fix some real time updates in group members

scripts/desktop/make-appimage-linux.sh
It was fixed: https://github.com/AppImage/type2-runtime/pull/82
=> desktop: start using continuous runtime for AppImage again

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/ChatModel.kt
30 and 31 of December messages were incorrectly showing as "31 December 2025", this was due to the year pattern used when formatting dates.
- `YYYY` (week-based year) can cause issues at the end of December or start of January.
- `yyyy` (calendar year) ensures you get the actual year of the LocalDateTime.
=> android, desktop: fix previous years display on chat view

apps/ios/Shared/Views/Chat/ChatView.swift, apps/ios/Shared/Views/Chat/Group/GroupMemberInfoView.swift, apps/ios/Shared/Views/ChatList/ChatPreviewView.swift, apps/ios/SimpleXChat/ChatTypes.swift, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/ChatModel.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/group/GroupMemberInfoView.kt, apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/item/ChatItemView.kt, apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml
Remove inline moderation options, after this changes:
- Moderators will no longer be able to press a report and get actions of moderation (moderate, block member), in order to do that they will need to navigate to original message (full support on android, desktop, support for already loaded items in ios, with full support coming soon)
- Archive context menu action on reports renamed "Archive report"
- Only user with role "member" will be able to submit reports
- Context menu options on reports for members: (delete, select)
- Context menu options on reports for admins, moderators, owners: (archive report, delete, select)
=> ui: remove support for inline moderation

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatView.kt
This prevents reply and handles the UI behavior the same way as other actions that are forbidden to reply on swipe (group events, invitations...)
=> android, desktop: prevent swipe reply on reports

install.sh
The Linux install got 404 cause the `platform` should be simplex-chat-ubuntu-`22_04-x86-64` or simplex-chat-ubuntu-`24_04-x86-64` and not `20_04-x86-64`.
in linux 
```shell
➜  simplex-chat git:(stable) uname
Linux
➜  simplex-chat git:(stable) bash install.sh 
downloading the latest version of SimpleX Chat ...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0      7      0  0:00:01  0:00:01 --:--:--     0
simplex-chat installed successfully!
Type simplex-chat in your terminal to run it
➜  simplex-chat git:(stable) which simplex-chat
/home/7sunarni/.local/bin/simplex-chat
➜  simplex-chat git:(stable) cat …
```
=> fix(install.sh): broken linux link
