simplex-chat/simplex-chat

readme.md

docs: comparison with P2P

---

LICENSE

docs: AGPL v3 license

---

simplex-messaging-implementation.md

Simplify API, remove connection ID, add single message API.
Closes #12

Simplify API, remove connection ID, add single message API

---

simplex-messaging-implementation.md

docs: websocket API, changed failed REST response codes

---

.github/workflows/build.yml
apps/simplex-chat/Main.hs
migrations/20210612_initial.sql
src/Simplex/Chat.hs
src/Simplex/Chat/Controller.hs
src/Simplex/Chat/Help.hs
src/Simplex/Chat/Protocol.hs
src/Simplex/Chat/Store.hs
src/Simplex/Chat/Types.hs
src/Simplex/Chat/View.hs
src/Simplex/Chat/protocol.md
stack.yaml
tests/ChatClient.hs
tests/ChatTests.hs

group commands (remove member, leave group, delete group)

---

README.md

:memo: Update readme install instructions

---

README.md

Removed horizontal lines - page looked a bit cluttered

Removed horizontal lines

---

apps/ios/Shared/ContentView.swift
apps/ios/Shared/Views/WelcomeView.swift

My first swift, be kind on review!

ios: display name validation

---

README.md

Related commits:
- https://github.com/simplex-chat/.github/pull/1 (depends on)
- https://github.com/simplex-chat/website/pull/15

readme: add fdroid badge

---

apps/simplex-bot-advanced/Main.hs
apps/simplex-bot/Main.hs
apps/simplex-chat/Main.hs
package.yaml
simplex-chat.cabal
src/Simplex/Chat/Bot.hs
src/Simplex/Chat/Options.hs

Merge to stable

---

apps/android/app/src/main/java/chat/simplex/app/MainActivity.kt
apps/android/app/src/main/java/chat/simplex/app/model/ChatModel.kt
apps/android/app/src/main/java/chat/simplex/app/model/NtfManager.kt
apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt
apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatView.kt
apps/android/app/src/main/java/chat/simplex/app/views/chatlist/ChatListView.kt
apps/android/app/src/main/java/chat/simplex/app/views/helpers/ModalView.kt

- Open all chats view from group notifications
- Clear overlays when opening from notification
- Clear notifications when chat opened even if not from that notification

android: notifications improvements (to stable)

---

README.md

* docs: contents, faq
* add app links to the bottom

docs: contents, faq (#729)

---

apps/android/app/src/main/java/chat/simplex/app/views/chat/ChatView.kt

- on orientation change scroll position in chat wasn't preserved
- the app had been making multiple same queries to a database when tried to preload more messages
Also optimized preloading of messages in terms of Compose code

Two fixes, better performance too

---

apps/android/app/src/main/java/chat/simplex/app/views/call/CallView.kt

- orientation will be locked in calls to portrait and then returned back
- calls ends audio session when they will be ended

android: prevent orientation change in calls

---

scripts/android/compress-and-sign-apk.sh

… the app when trying to open .mp3 file from the directory

android: disable compression of `res/raw` directory to avoid crash on incoming call (opening mp3)

---

apps/android/app/src/main/java/chat/simplex/app/views/chatlist/ChatListNavLinkView.kt
apps/android/app/src/main/java/chat/simplex/app/views/chatlist/ChatListView.kt
apps/android/app/src/main/res/values-ru/strings.xml
apps/android/app/src/main/res/values/strings.xml

- also fixed two-line preview in a chat list

android: floating button for creating a new chat

---

apps/android/app/src/main/java/chat/simplex/app/views/helpers/ModalView.kt
apps/android/app/src/main/java/chat/simplex/app/views/newchat/ConnectViaLinkView.kt
apps/android/app/src/main/java/chat/simplex/app/views/newchat/NewChatSheet.kt
apps/android/app/src/main/java/chat/simplex/app/views/newchat/PasteToConnect.kt
apps/android/app/src/main/java/chat/simplex/app/views/newchat/ScanToConnectView.kt

android: Closing qr scanner/connect via link screens after successfull request

---

apps/android/app/src/main/AndroidManifest.xml
apps/android/app/src/main/java/chat/simplex/app/model/NtfManager.kt
apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt
apps/android/app/src/main/res/values-de/strings.xml
apps/android/app/src/main/res/values-ru/strings.xml
apps/android/app/src/main/res/values/strings.xml

android: Two more notifications when contact connected or connection request received

---

apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/de.lproj/Localizable.strings

Some corrections inside the German translations for iOS --> de.xliff

ios: update german translation

---

apps/android/app/src/main/java/chat/simplex/app/views/usersettings/Appearance.kt
apps/android/app/src/main/java/chat/simplex/app/views/usersettings/NotificationsSettingsView.kt
apps/android/app/src/main/java/chat/simplex/app/views/usersettings/RTCServers.kt
apps/android/app/src/main/java/chat/simplex/app/views/usersettings/SMPServers.kt

Follow up for prev ui-overhaul PR

android: Dividers and padding

---

apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/de.lproj/Localizable.strings

ios: german translations added and fixed

ios: german translations for v4.1

---

apps/android/app/src/main/res/values-de/strings.xml
apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/de.lproj/Localizable.strings

android / iOS: german translations added and fixed

android / iOS: german translations for v4.2

---

apps/android/app/src/main/res/values-de/strings.xml
apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/SimpleXChat/APITypes.swift
apps/ios/de.lproj/Localizable.strings

android / iOS: german translations added and fixed

android / iOS: german translations for 4.2

---

apps/android/app/src/main/res/values-de/strings.xml
apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/de.lproj/Localizable.strings

android / iOS: german translations fixed

android / iOS: german translations for 4.2.1

---

apps/android/app/src/main/res/values-de/strings.xml
apps/ios/SimpleX Localizations/de.xcloc/Localized Contents/de.xliff
apps/ios/de.lproj/Localizable.strings
apps/ios/de.lproj/SimpleX--iOS--InfoPlist.strings

android / iOS: german translations added and fixed

mobile: German translations for 4.3

---

apps/android/app/src/main/java/chat/simplex/app/views/chat/ComposeView.kt
apps/android/app/src/main/java/chat/simplex/app/views/helpers/GetImageView.kt

android: Show user's camera when system camera is unavailable

---

apps/android/app/src/main/java/chat/simplex/app/views/chat/item/TextItemView.kt

android: No crash when clicking on a link with unknown activity action

---

apps/android/app/src/main/java/chat/simplex/app/model/NtfManager.kt
apps/android/app/src/main/java/chat/simplex/app/views/call/IncomingCallActivity.kt
apps/android/app/src/main/java/chat/simplex/app/views/call/IncomingCallAlertView.kt

android: fix full screen call notification

---

apps/android/app/src/main/AndroidManifest.xml
apps/android/app/src/main/java/chat/simplex/app/MainActivity.kt

- Android versions <= 10 are vulnerable to StrandHogg 1. This commit fixes the behavior of the app on affected versions of Android

android: Change of launchMode in an activity and different behavior of back button

---

apps/android/app/src/main/java/chat/simplex/app/SimplexApp.kt

android: Fix for AddressAlreadyInUse exception

---

apps/ios/SimpleX Localizations/fr.xcloc/Localized Contents/fr.xliff

Currently translated at 97.6% (785 of 804 strings)
Translation: SimpleX Chat/SimpleX Chat iOS
Translate-URL: https://hosted.weblate.org/projects/simplex-chat/ios/fr/

translations

---

apps/android/app/src/main/java/chat/simplex/app/model/ChatModel.kt
apps/android/app/src/main/res/values-de/strings.xml
apps/android/app/src/main/res/values-fr/strings.xml
apps/android/app/src/main/res/values-it/strings.xml
apps/android/app/src/main/res/values-ru/strings.xml
apps/android/app/src/main/res/values/strings.xml

android: add localization of "offered/cancelled" feature items, closes #1766

---

apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt
apps/ios/Shared/Model/NtfManager.swift
apps/ios/Shared/Model/SimpleXAPI.swift
apps/ios/Shared/Views/Chat/ChatItem/CIFileView.swift
apps/ios/Shared/Views/Chat/ChatItem/CIImageView.swift

Almost same as https://github.com/simplex-chat/simplex-chat/pull/1846
except: 
https://github.com/simplex-chat/simplex-chat/pull/1874/files#diff-e0a2bb9b82bd2636c5e187aa0b5c942c039c21031030f0558215e01d53165e7eR92
https://github.com/simplex-chat/simplex-chat/pull/1874/files#diff-2d8946cfd687e008b341621c431c8e9ed31265d5f857d094ebd87d27aaf9a4a4R1109

ios: show notifications for different users

---

docs/guide/audio-video-calls.md

Added some initial documentation for audio and video calls.

guide:  initial documentation for audio and video calls

---

apps/android/app/src/main/java/chat/simplex/app/MainActivity.kt

android: change active user after chat started

---

apps/android/app/src/main/java/chat/simplex/app/model/SimpleXAPI.kt
apps/android/app/src/main/java/chat/simplex/app/views/usersettings/NetworkAndServers.kt
apps/android/app/src/main/res/values-ar/strings.xml
apps/android/app/src/main/res/values-cs/strings.xml
apps/android/app/src/main/res/values-de/strings.xml
apps/android/app/src/main/res/values-es/strings.xml
apps/android/app/src/main/res/values-fr/strings.xml
apps/android/app/src/main/res/values-it/strings.xml
apps/android/app/src/main/res/values-ja/strings.xml
apps/android/app/src/main/res/values-ko/strings.xml
apps/android/app/src/main/res/values-lt/strings.xml
apps/android/app/src/main/res/values-nl/strings.xml
apps/android/app/src/main/res/values-pl/strings.xml
apps/android/app/src/main/res/values-pt-rBR/strings.xml
apps/android/app/src/main/res/values-ru/strings.xml
apps/android/app/src/main/res/values-zh-rCN/strings.xml
apps/android/app/src/main/res/values-zh-rTW/strings.xml
apps/android/app/src/main/res/values/strings.xml

android: socks proxy port

---

simplex-chat.cabal

add cabal.project to extra-source-files

---

website/langs/en.json

Fixed typo in en.json

---

scripts/desktop/make-appimage-linux.sh

Resulting AppImage can be found here: https://github.com/avently/simplex-chat/releases/tag/v1.0.10

desktop: AppImage support

---

apps/ios/Shared/Views/Helpers/ImagePicker.swift

How to correctly load video selected with PHPickerViewController? - https://developer.apple.com/forums/thread/652695?answerId=629922022#629922022
https://developer.android.com/guide/topics/media/platform/supported-formats

ios: making thumbnails faster

---

.github/workflows/build.yml
apps/multiplatform/build.gradle.kts
scripts/desktop/build-desktop-mac-ci.sh

https://github.com/avently/simplex-chat/actions/runs/5988345573/job/16243432366

desktop: fixed gradle

---

src/Simplex/Chat.hs
tests/ChatClient.hs
tests/ChatTests/Groups.hs

core: update contact and member profiles for both sides when contact is created with member (WIP)

---

src/Simplex/Chat.hs
src/Simplex/Chat/Controller.hs

Put them closer to `ChatMonad` definition to promote extracting code from the `Controller.hs`.

Extract toView and withStore* to a common module

---

blog/20230925-simplex-chat-v5-3-desktop-app-local-file-encryption-directory-service.md

`you know` instead of `your know`

just typo in latest blog post

---

flake.lock
flake.nix

Bumps hackage
```
nix flake lock --update-input hackage 
```
also updates the index-state in the flake.nix

bump hackage

---

flake.nix

nix: fix lib:support for armv7a

---

apps/multiplatform/common/src/commonMain/cpp/android/simplex-api.c
apps/multiplatform/common/src/commonMain/cpp/desktop/simplex-api.c

* Larger initial heap for faster startup.
* Larger arena size for less frequent GC.

android, desktop: set RTS options for core

---

cabal.project
flake.lock
flake.nix
package.yaml
scripts/nix/sha256map.nix
simplex-chat.cabal

Crypton added hashing of the RNG seed on top of Cryptonite (that is no longer maintained).

core: use crypton instead of cryptonite

---

apps/ios/Shared/Views/Helpers/ImagePicker.swift

This reverts commit cd9cb8e064b3df1902c5c2321556b0ca1dc5e9b8.

ios: revert "ios: making thumbnails faster" (makes iOS videos more compatible)

---

apps/ios/Shared/Views/Chat/ComposeMessage/ComposeView.swift
apps/ios/Shared/Views/Helpers/ImagePicker.swift
apps/ios/Shared/Views/Helpers/VideoUtils.swift
apps/ios/SimpleX.xcodeproj/project.pbxproj

Lower quality allows to play that videos on Android as well

ios: converting video to mp4 and making quality lower

---

apps/ios/Shared/Views/Onboarding/CreateProfile.swift
apps/ios/SimpleXChat/APITypes.swift
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/SimpleXAPI.kt
apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml

Follow up to: https://github.com/simplex-chat/simplex-chat/pull/3647

mobile, desktop: invalid display name alert

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/item/ChatItemView.kt

Checked on Linux, mac, Android

desktop: alignment for reactions

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/Utils.kt
apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/platform/Images.desktop.kt

https://stackoverflow.com/a/57264490

desktop: better decoding Android's base64 encoded image

---

cabal.project
package.yaml
scripts/nix/sha256map.nix
simplex-chat.cabal
src/Simplex/Chat.hs
src/Simplex/Chat/Messages.hs
src/Simplex/Chat/Mobile.hs
src/Simplex/Chat/Mobile/WebRTC.hs
src/Simplex/Chat/Remote.hs
src/Simplex/Chat/Store/Shared.hs
tests/ChatTests/Utils.hs
tests/WebRTCTests.hs

This reverts commit d65137882bfd822d4af4aaf98871f1dd98efebde.

core: revert "deps: switch to base64 via simplexmq (#3957)"

---

docs/FAQ.md

As discussed in SimpleX Chat with the developer(s), I created a basic FAQ.md for new users.

Added FAQ.md

---

apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/views/call/CallAudioDeviceManager.kt
apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/views/call/CallView.android.kt
apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml

It's a second part of changes. Mainly for Android <= 11 but there are changes for newer ones as well

android: managing audio sources in call in a better way

---

docs/protocol/simplex-chat.md

docs: typo in simplex-chat.md

---

apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/platform/Share.android.kt
apps/multiplatform/common/src/androidMain/kotlin/chat/simplex/common/views/helpers/Utils.android.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/model/ChatModel.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ComposeView.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/item/CIFileView.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/item/ImageFullScreenView.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/helpers/Utils.kt
apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/platform/Share.desktop.kt
apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/views/chat/item/ChatItemView.desktop.kt
apps/multiplatform/common/src/desktopMain/kotlin/chat/simplex/common/views/helpers/Utils.desktop.kt

android, desktop: alert for local encryption/decryption errors

---

apps/ios/SimpleXChat/APITypes.swift
apps/ios/SimpleXChat/ChatTypes.swift

Part of `Timeline` feature:
1. [Hashable Conformance](https://github.com/simplex-chat/simplex-chat/pull/4348)
2. [Views](https://github.com/simplex-chat/simplex-chat/pull/4350)
3. [Integration](https://github.com/simplex-chat/simplex-chat/pull/4351)
[UICollectionViewDiffableDataSource](https://developer.apple.com/documentation/uikit/uicollectionviewdiffabledatasource) uses hash values, 
to drive cell state updates and provide coherent animations. 
This PR adds (mostly) synthesised conformance to chat and API types.

iOS Timeline: 1. Hashable Conformance

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/database/DatabaseView.kt

Follow up:
https://github.com/simplex-chat/simplex-chat/pull/4313/files

android, desktop: close modals only for desktop

---

apps/ios/Shared/Views/Helpers/ChatItemClipShape.swift
apps/ios/Shared/Views/UserSettings/AppearanceSettings.swift

ios: make message corners rounded in theme preview

---

apps/ios/Shared/Views/Helpers/ChatInfoImage.swift
apps/ios/SimpleX SE/ShareView.swift
apps/ios/SimpleXChat/ChatUtils.swift

Matches row height, compose background material and fallback icons used for various chat types.

ios: match share sheet ui with forward sheet

---

apps/ios/Shared/Views/ChatList/ChatListView.swift

- fix sheet layout in one hand mode
- move user picker to bottom in one hand mode

layout fixes

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatView.kt

Fixes problems introduced in https://github.com/simplex-chat/simplex-chat/pull/4567

android, desktop: fix chatView state propagation

---

apps/ios/Shared/Model/ChatModel.swift
apps/ios/Shared/Model/SimpleXAPI.swift
apps/ios/Shared/Views/Chat/ChatInfoView.swift
apps/ios/Shared/Views/Chat/Group/GroupMemberInfoView.swift
apps/ios/Shared/Views/ChatList/ChatPreviewView.swift

- moves networkStatuses into a separate model

ios: speed up network status handling

---

website/langs/uk.json

Currently translated at 100.0% (257 of 257 strings)
Translation: SimpleX Chat/SimpleX Chat website
Translate-URL: https://hosted.weblate.org/projects/simplex-chat/website/uk/

website: translation

---

apps/ios/Shared/Views/Chat/ChatItem/FramedItemView.swift

ios:  remove [Copy | Share...] context menu from chat message

---

apps/ios/Shared/AppDelegate.swift
apps/ios/Shared/Model/ChatModel.swift
apps/ios/Shared/Views/Migration/MigrateFromDevice.swift
apps/ios/Shared/Views/Migration/MigrateToDevice.swift
apps/ios/Shared/Views/NewChat/NewChatView.swift
apps/ios/Shared/Views/UserSettings/AppSettings.swift
apps/ios/SimpleX.xcodeproj/project.pbxproj
apps/ios/SimpleX.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
apps/ios/SimpleXChat/SimpleX.h
apps/ios/SimpleXChat/objc.h
apps/ios/SimpleXChat/objc.m
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/migration/MigrateFromDevice.kt
apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/migration/MigrateToDevice.kt
apps/multiplatform/common/src/commonMain/resources/MR/base/strings.xml
cabal.project
scripts/nix/sha256map.nix
src/Simplex/Chat/Store/Shared.hs

TODO: fix error after migration failure

fix incorrect error of migration to device

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/newchat/NewChatView.kt

Was broken while making this composable reusable for switching profile in share from external source to app.
Tested both scenarios

android, desktop: fix profile switching failure handling

---

apps/multiplatform/common/src/commonMain/kotlin/chat/simplex/common/views/chat/ChatItemInfoView.kt

- changed tabBar style to leading icon
- made tabBar the same size as AppBars
- made background color as theme background

android, desktop: better message info screen

---

docs/FAQ.md

Added:
- Why invite links use simplex.chat domain?
- I do not know my database passphrase

docs: update FAQ

---

website/langs/ru.json

Currently translated at 100.0% (258 of 258 strings)
Translation: SimpleX Chat/SimpleX Chat website
Translate-URL: https://hosted.weblate.org/projects/simplex-chat/website/ru/

website: translations

---

apps/simplex-directory-service/src/Directory/Captcha.hs
simplex-chat.cabal
tests/Bots/DirectoryTests.hs

directory: use lowercase letters in captcha, accept any case for same-looking letters

---

packages/simplex-chat-client/typescript/README.md

docs: readme typo

---

bots/README.md

Add community made bot for bridging between different platforms.

doc(bots): add bridge bot
